Scoring and typing
tessapower/ggj-2024 pull request #27
Opened 2024-01-25 06:35 UTC by ZedXC

a new minigame + attention bar and chances to how the game scores and functions around ending games and beginning new ones.

2024-01-25 20:24 UTC, tessapower requested changes
Some architectural changes and a few bugs to look into!

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scenes/mini_games/typ5A4C.tmp
This temp file should be deleted.

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scenes/mini_games/typ6DF3.tmp
This temp file should be deleted.

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scripts/game.gd
> +  decrease_attention_meter(10)
Godot is complaining about incorrect indentation here, so it stops the game from running.

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scripts/game.gd
> +	attention_meter_instance.set_attention(attention_change)
These functions should really be removed in favor of the attention meter data being stored in the Gamestate Manager and the attention meter scene itself requesting that data from the Gamestate Manager to know what to display at any given point in time. Doing so will keep all player related data in one place, and the logic for when the game is over in the logical place.

This will also make it easier for each mini-game to update the score and attention meter appropriately by going through the Gamestate Manager, also removing the need for the `on_finished` function in the `game` script to do anything other than load the next random mini-game.

Seeing as we only want update the attention meter based on the player's performance, we would ideally have a function that takes an enum and uses a match statement (Godot's version of a switch) to do this, calling this function at the appropriate time in the mini-game's lifecycle from the mini-game's own script - this will allow each mini-game to decide the right way to evaluate performance.

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scripts/mini_games/typingMinigame.gd
We need to change how the player pauses the game, possibly by adding a button, as typing 'p' pauses the game so I can't type any punchline that contains a 'p'.

2024-01-25 20:24 UTC, tessapower commented on jest-to-impress/scripts/mini_games/typingMinigame.gd
I'm unsure how it happened, but I can only play this mini-game once on the first play through, and every subsequent play through this mini-game doesn't show up.

2024-01-26 01:43 UTC, ZedXC commented on jest-to-impress/scripts/mini_games/typingMinigame.gd
Could we change the pause button to be esc instead of P? I feel like thats more intuitive?

2024-01-26 01:45 UTC, ZedXC commented on jest-to-impress/scripts/game.gd
> +  decrease_attention_meter(10)
ah that was when I fixed the merge conflicts. easy solve

2024-01-27 00:18 UTC, tessapower approved these changes

2024-01-27 00:18 UTC, merged